service: simple-queue-writer

# ------------------ APP SETTINGS------------------- #
server:
  port: 8080

# ------------------ AWS SETTINGS------------------- #
aws:
  region: eu-central-1
  sqs:
    queue_name: myTestQueue
    queue_url: https://sqs.eu-central-1.amazonaws.com/891377221874/myTestQueue