service: simple-queue-writer

# ------------------ APP SETTINGS------------------- #
server_port: 8080

# ------------------ AWS SETTINGS------------------- #
STAGE:
REGION:
AWS_SQS_QUEUE_NAME:
AWS_SQS_QUEUE_URL: https://sqs.eu-central-1.amazonaws.com/891377221874/test